--
-- Volcado de datos para la tabla `audit_cliente` INSURER
--

INSERT INTO "Insurer" (identity, name, insurer_type, logo) VALUES
(1, 'PRX CONSULTING', 1, ''),
(2, 'MERCANTIL SEGUROS, C.A.', 2, 'mercantil.png'),
(3, 'LATAM HEALTH SOLUTIONS', 2, ''),
(4, 'HUMANITAS', 2, 'humanitas.png'),
(5, 'MAPFRE', 2, 'mapfre.png'),
(6, 'SEGUROS VENEZUELA', 2, ''),
(7, 'SEGUROS CARACAS', 2, 'seguros_caracas.png'),
(8, 'SEGUROS PIRAMIDE', 2, ''),
(10, 'AUXIMED', 1, ''),
(11, 'ADRIATICA DE SEGUROS', 2, ''),
(12, 'BANESCO SEGUROS', 2, 'banesco.png'),
(13, 'ESTAR SEGUROS', 2, 'estarseguros.png'),
(14, 'HISPANA DE SEGUROS', 2, ''),
(15, 'IBEROAMERICANA DE SEGUROS', 2, ''),
(16, 'INTERBANK SEGUROS', 2, ''),
(17, 'LA REGIONAL DE SEGUROS', 2, ''),
(18, 'LA VENEZOLANA DE SEGUROS', 2, ''),
(19, 'MAKLER', 2, 'makler.png'),
(20, 'MULTINACIONAL DE SEGUROS', 2, ''),
(21, 'NUEVO MUNDO SEGUROS', 2, ''),
(22, 'OCEANICA DE SEGUROS', 2, ''),
(23, 'ORIENTAL DE SEGUROS', 2, ''),
(24, 'PLANINSA', 2, ''),
(25, 'PRIMUS SEGUROS', 2, ''),
(26, 'PROSEGUROS', 2, ''),
(27, 'RONTARCA', 2, ''),
(28, 'SEGUROS ALTAMIRA', 2, ''),
(29, 'SEGUROS AMERICAN INTERNATIONAL (AIG)', 2, ''),
(30, 'SEGUROS AVILA', 2, ''),
(31, 'SEGUROS BANVALOR', 2, ''),
(32, 'SEGUROS CANARIAS DE VENEZUELA', 2, ''),
(33, 'SEGUROS CARABOBO', 2, 'carabobo.png'),
(34, 'SEGUROS CARONI', 2, 'caroni.png'),
(35, 'SEGUROS CATATUMBO', 2, ''),
(36, 'SEGUROS COMERCIALES BOLIVAR', 2, ''),
(37, 'SEGUROS CONSTITUCION', 2, ''),
(38, 'SEGUROS CORPORATIVOS', 2, ''),
(39, 'SEGUROS DE CREDITO LA MUNDIAL', 2, ''),
(40, 'SEGUROS FEDERAL', 2, ''),
(41, 'SEGUROS GUAYANA', 2, ''),
(42, 'SEGUROS HORIZONTE', 2, ''),
(43, 'SEGUROS LA FE', 2, ''),
(44, 'SEGUROS LA INTERNACIONAL', 2, ''),
(45, 'SEGUROS LA OCCIDENTAL', 2, ''),
(46, 'SEGUROS LA PREVISORA', 2, ''),
(47, 'SEGUROS LA VITALICIA', 2, ''),
(48, 'SEGUROS LOS ANDES', 2, ''),
(49, 'SEGUROS PROVINCIAL', 2, ''),
(50, 'SEGUROS QUALITAS', 2, 'qualitas.png'),
(51, 'SEGUROS UNIVERSITA', 2, ''),
(52, 'SEGUROS VIRGEN DEL VALLE', 2, ''),
(53, 'TRANSEGURO', 2, ''),
(54, 'UNISEGUROS', 2, ''),
(55, 'UNIVERSAL DE SEGUROS', 2, ''),
(56, 'ZUMA SEGUROS', 2, ''),
(57, 'AUDITIA', 2, ''),
(58, 'DEMO', 1, ''),
(59, 'ZURICH SEGUROS', 2, ''),
(60, 'AON', 2, 'aon.png'),
(61, 'SANITAS VENEZUELA', 2, 'sanitas.png');
