--
-- Volcado de datos para la tabla `tipo_diagnostico` DIAGNOSIS
--

INSERT INTO "Diagnosis" (code, name, description, keywords, cie10) VALUES
(9, 'ABORTO RETENIDO', 'Es la expulsión del feto antes de llegar a la viabilidad de la capacidad del feto de poder sobrevivir \r\nfuera del vientre materno.\r\n', '', 'O02'),
(10, 'NEUMONIA VIRAL ', 'La neumonía es una enfermedad que se caracteriza por la inflamación de los pulmones, causada por virus, hongos o bacterias. Los síntomas de la neumonía son: tos, fiebre, dificultades para respirar y malestar general. La neumonía también puede ser causada por el tabaco.  ', '', 'J12'),
(11, 'SINDROME ARTERIAL VERTEBRO-BASILAR', '', '', 'G45'),
(15, 'CANDIDIASIS PULMONAR', '', '', 'B371'),
(16, 'CANDIDIASIS DE LA PIEL Y DE LAS UÑAS', '', '', 'B372'),
(17, 'MENINGITIS DEBIDA A CANDIDA', '', '', 'B375'),
(18, 'SEPTICEMIA DEBIDA A CANDIDA', '', '', 'B377'),
(19, 'PROCTITIS (CRONICA) ULCERATIVA', '', '', 'K51'),
(20, 'RECTOSIGMOIDITIS (CRONICA) ULCERATIVA', '', '', 'K51'),
(21, 'SEUDOPOLIPOSIS DEL COLON', '', '', 'K51'),
(22, 'PROCTOCOLITIS MUCOSA', ' ', '', 'K51'),
(23, 'MIALGIA', 'Las mialgias consisten en dolores musculares que pueden afectar a uno o varios músculos del cuerpo y pueden estar producidos por causas muy diversas. Estos dolores musculares pueden acompañarse en ocasiones de debilidad o pérdida de la fuerza y dolor a la palpación. También se asocia en ocasiones con calambres y contracturas de los músculos afectados.', '', 'M79'),
(24, 'DISTENSION MUSCULAR', '', '', 'M62'),
(25, 'TRASTORNO MUSCULAR', ' ', '', 'M62'),
(26, 'SINDROME DE INMOVILIDAD (PARAPLEJICO)', '', '', 'M62'),
(27, 'CONTRACTURA MUSCULAR', 'Una contractura muscular es la contracción involuntaria, de una manera continua, de los músculos. La contractura muscular más común ocurre en la zona inferior de la espalda. ', '', 'M62'),
(28, 'ACANTOSIS NIGRICANS', 'Es una enfermedad caracterizada por la presencia de hiperqueratosis e hiperpigmentación en los pliegues cutáneos perianales y axilares. Se caracteriza por lesiones de color gris - parduzco y engrosadas, que dan un aspecto verrucoso y superficie aterciopelada. ', '', 'L83'),
(29, 'HALLUX VALGUS (ADQUIRIDO)', '', '', 'M20'),
(30, 'HALLUX RIGIDUS', '', '', 'M20'),
(31, 'DERMATITIS ATOPICA', 'La dermatitis es una patología que caracteriza por erupciones en la piel producidas por el contacto con sustancias tóxicas e irritantes. En otras palabras, la dermatitis es una alergia en la piel. La dermatitis puede ser producida por materiales y sustancias tóxicas como ácidos, detergentes, químicos, etc. ', '', 'L20'),
(32, 'ACCIDENTE CEREBRO VASCULAR (ACV) NO HEMORRAGICO', 'Un accidente cerebro vascular es una enfermedad que se caracteriza por la interrupción de suministro de flujo sanguíneo al cerebro. La interrupción del flujo sanguíneo puede ocurrir por el bloqueo o ruptura de un vaso sanguíneo. Al interrumpir el flujo sanguíneo, el cerebro deja de recibir oxígeno y sangre, causando la muerte a células cerebrales y así mismo provocando daños permanentes.  Los causantes de los ACV son: la hipertensión arterial , la diabetes , la dislipidemia entre otras.', '', 'I64'),
(33, 'RETINOSQUISIS', '', '', 'H33'),
(34, 'QUISTES DE LA RETINA (DERMOIDE)', '', '', 'H33'),
(35, 'ACIDEZ O PIROSIS', 'La acidez gástrica es una patología que ocurre cuando el esfínter esofágico (músculo que cierra la tapa del estómago) no cierra bien y permite que los ácidos gástricos se devuelvan al esófago. La acidez gástrica se siente como un ardor en el pecho, garganta y cuello. La acidez gástrica se siente generalmente después de comer, al debilitarse el esfínter esofágico. ', '', 'R12'),
(36, 'AGNOSIA', '', '', 'R48'),
(37, 'TROMBOANGEITIS OBLITERANTE [BUERGER]', 'Exceso de ácido en la orina.', '', 'I73'),
(38, 'ENFERMEDAD DE LOS LEGIONARIOS', '', '', 'A48'),
(39, 'ENFERMEDAD DE LOS LEGIONARIOS NO NEUMONICA [FIEBRE DE PONTIAC]', '', '', 'A48'),
(40, 'SINDROME DE CHOQUE TOXICO', '', '', 'A48'),
(41, 'FIEBRE PURPURICA BRASILEÑA', '', '', 'A48'),
(42, 'HIPERESPLENISMO', '', '', 'D73'),
(43, 'ESPLENOMEGALIA CONGESTIVA CRONICA', '', '', 'D73'),
(44, 'ABSCESO DEL BAZO', '', '', 'D73'),
(45, 'QUISTE DEL BAZO', '', '', 'D73'),
(46, 'INFARTO DEL BAZO', '', '', 'D73'),
(47, 'ABSCESO DEL TIMO', '', '', 'E32'),
(48, 'SEPTICEMIA DEBIDA A SALMONELLA', '', '', 'A02'),
(49, 'GASTROENTEROCOLITIS', '', '', 'K52'),
(51, 'OFTALMOPLEJIA EXTERNA PROGRESIVA', '', '', 'H49'),
(52, 'EXANTEMA SUBITO [SEXTA ENFERMEDAD]', '', '', 'B082'),
(53, 'ERITEMA INFECCIOSO [QUINTA ENFERMEDAD]', '', '', 'B083'),
(54, 'ESTOMATITIS VESICULAR ENTEROVIRAL CON EXANTEMA', '', '', 'B084'),
(55, 'FARINGITIS VESICULAR ENTEROVIRICA', 'Lesión tumoral maligna de naturaleza epitelial, con formación de estructuras glandulares reconocibles u originadas a partir de un epitelio glandular. Existen varios tipos según la estructura dominante.', '', 'B085'),
(65, 'FIEBRE PARATIFOIDEA A', '', '', 'A01'),
(67, 'FIEBRE PARATIFOIDEA B', '', '', 'A01'),
(68, 'FIEBRE PARATIFOIDEA C', '', '', 'A01'),
(69, 'GIARDIASIS [LAMBLIASIS]', '', '', 'A07'),
(70, 'ISOSPORIASIS', '', '', 'A07'),
(72, 'PERIODONTITIS AGUDA', '', '', 'K05'),
(73, 'PERIODONTITIS CRONICA', '', '', 'K05');

