--
-- Volcado de datos para la tabla `tipo_diagnostico1` 	TYPE OF DIAGNOSIS
--

INSERT INTO "Type_of_diagnosis" (code, description) VALUES
('AB', 'CIERTAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS'),
('AD', 'AUTODIAGNOSTICO'),
('C', 'NEOPLASIAS'),
('CI', 'CIRUGIAS, EXAMENES Y PROCEDIMIENTOS'),
('D', 'ENFERMEDADES DE LA SANGRE Y DE LOS ORGANOS HEMATOPOYETICOS Y OTROS TRASTORNOS QUE AFECTAN EL MECANISMO DE LA INMUNIDAD'),
('E', 'ENFERMEDADES ENDOCRINAS, NUTRICIONALES Y METABOLICAS '),
('F', 'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO'),
('G', 'ENFERMEDADES DEL SISTEMA NERVIOSO'),
('H1', 'ENFERMEDADES DEL OJO Y SUS ANEXOS'),
('H2', 'ENFERMEDADES DEL OIDO Y DE LA APOFISIS MASTOIDES'),
('I', 'ENFERMEDADES DEL SISTEMA CIRCULATORIO'),
('J', 'ENFERMEDADES DELSISTEMA RESPIRATORIO'),
('K', 'ENFERMEDADES DEL APARATO DIGESTIVO'),
('L', 'ENFERMEDADES DE LA PIEL Y EL TEJIDO SUBCUTANEO'),
('M', 'ENFERMEDADES DEL SISTEMA OSTEOMUSCULAR Y DEL TEJIDO CONECTIVO'),
('N', 'ENFERMEDADES DEL APARATO GINTOURINARIO'),
('NO', 'NO DISPONIBLE'),
('O', 'EMBARAZO, PARTO Y PUERPERIO'),
('P', 'CIERTAS AFFECIONES ORIGINADAS EN EL PERIODO PERINATAL'),
('Q', 'MALFORMACIONES CONGENITAS, DEFORMIDADES Y ANOMALIAS CROMOSOMICAS'),
('R', 'SINTOMAS, SIGNOS Y HALLAZGOS ANORMALES CLINICOS Y DE LABORATORIO, NO CLASIFICADOS EN OTRA PARTE'),
('ST', 'TRAUMATISMOS, ENVENENAMIENTOS Y ALGUNAS OTRAS CONSECUENCIAS DE CAUSA EXTERNA  '),
('U', 'SITUACIONES ESPECIALES'),
('VY', 'CAUSAS EXTREMAS DE MORBILIDAD Y MORTALIDAD'),
('Z', 'FACTORES QUE INCLUYEN EN EL ESTADO DE SALUD Y CONTACTO CON LOS SERVICIOS DE SALUD');

